version: '3.4'

services:
  shortex.client:
    image: ${DOCKER_REGISTRY-}shortexclient
    build:
      context: .
      dockerfile: Shortex.Client/Dockerfile
    ports:
        - "8080:80"
    depends_on:
        - shortex.db

  shortex.db:
      image: "mcr.microsoft.com/mssql/server:2022-latest"
      ports:
        - "1433:1433"
      environment:
          SA_PASSWORD: "Url_Shortener"
          ACCEPT_EULA: "Y"